# Generated by Django 2.2 on 2021-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourierId', models.CharField(max_length=10)),
                ('From_Name', models.CharField(max_length=20)),
                ('Product_Name', models.IntegerField(max_length=30)),
                ('weight', models.CharField(max_length=10)),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='courier_booking',
            name='CourierId',
            field=models.IntegerField(),
        ),
    ]
