# Generated by Django 2.2 on 2021-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_tracking', '0002_auto_20210308_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier_booking',
            name='From_EmailAddress',
            field=models.CharField(max_length=40),
        ),
    ]
